<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Home | Wardrobe Alpha Edge</title><meta name="description" content="Wardrobe Alpha Edge — modern wardrobe craft, fit, layers and responsible style guidance."><link rel="stylesheet" href="assets/style.css"><script async src="https://www.googletagmanager.com/gtag/js?id=G-0LY0HY7L01"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments)}gtag('consent','default',{analytics_storage:'denied',ad_storage:'denied',ad_user_data:'denied',ad_personalization:'denied'});gtag('js',new Date());gtag('config','G-0LY0HY7L01');</script></head><body>
<header><div class="nav"><a class="brand" href="index.php">WARDROBE ALPHA EDGE</a><nav><a href="index.php">Home</a><a href="collection.html">Collection</a><a href="journal.html">Journal</a><a href="about.html">Atelier</a><a href="contact.html">Contact</a></nav></div></header>
<main>
<section class="wrap hero reveal"><div><div class="kicker">Wardrobe intelligence / 01</div><h1>Build a wardrobe with a sharper point of view.</h1><p>Wardrobe Alpha Edge explores fit, fabric, layering and everyday dressing through practical editorial guidance. Discover pieces by purpose, season and silhouette, then build a wardrobe that feels considered rather than crowded.</p><a class="btn" href="collection.html">Explore the system</a></div><img src="assets/hero.svg" alt="Editorial wardrobe silhouette"></section>
<section class="section"><div class="wrap"><div class="kicker">01 — The edit</div><h2>Four coordinates for better dressing.</h2><p class="lead">Start with proportion, then add texture, weather logic and repeatable combinations. The goal is a flexible wardrobe that earns its space.</p><div class="mosaic"><div class="tile"><img src="assets/silhouette.svg" alt=""><h3>Silhouette</h3><p>Use shape to create visual rhythm without overcomplicating an outfit.</p></div><div class="tile"><img src="assets/fabric.svg" alt=""><h3>Material</h3><p>Compare weight, hand feel and durability before choosing a fabric.</p></div><div class="tile"><img src="assets/layer.svg" alt=""><h3>Layering</h3><p>Build useful combinations around temperature and movement.</p></div></div></div></section>
<section class="section"><div class="wrap split"><div><div class="kicker">02 — Fit index</div><h2>Measure the mood, not just the garment.</h2><p class="lead">A useful fit is one that supports the way you actually move. Use these simple checkpoints before deciding whether a piece belongs.</p></div><div><div class="stat"><span>Shoulder line</span><b>01</b></div><div class="stat"><span>Ease through body</span><b>02</b></div><div class="stat"><span>Sleeve balance</span><b>03</b></div><div class="stat"><span>Hem relationship</span><b>04</b></div></div></div></section>
<section class="section"><div class="wrap"><div class="kicker">03 — Seasonal compass</div><h2>Dress for the day you have.</h2><div class="grid"><div class="card"><img src="assets/season.svg" alt=""><span class="tag">Spring</span><h3>Light layers</h3><p>Breathable overshirts, easy trousers and adaptable outer layers.</p></div><div class="card"><img src="assets/weather.svg" alt=""><span class="tag">Autumn</span><h3>Texture first</h3><p>Use wool, brushed cotton and structured layers for depth.</p></div><div class="card"><img src="assets/travel.svg" alt=""><span class="tag">Travel</span><h3>Repeatable sets</h3><p>Choose pieces that can cross several outfits without feeling repetitive.</p></div></div></div></section>
<section class="section"><div class="wrap split"><div><div class="kicker">04 — Wardrobe motion</div><h2>See the week as a sequence.</h2><p class="lead">Instead of planning isolated outfits, map the week by activity: work, travel, evening, recovery and weather changes.</p></div><img src="assets/urban.svg" alt="Urban wardrobe editorial"></div></section>
<section class="section"><div class="wrap"><div class="kicker">05 — Craft notes</div><h2>Details that make a garment stay relevant.</h2><div class="mosaic"><div class="tile"><img src="assets/detail.svg" alt=""><h3>Construction</h3><p>Look at seams, closures and stress points before surface decoration.</p></div><div class="tile"><img src="assets/craft.svg" alt=""><h3>Finish</h3><p>Finishing choices can change how a piece ages and layers.</p></div><div class="tile"><img src="assets/care.svg" alt=""><h3>Care</h3><p>Simple maintenance often extends the useful life of clothing.</p></div></div></div></section>
<section class="section"><div class="wrap split"><div><div class="kicker">06 — The archive</div><h2>Keep fewer pieces, but know why they work.</h2><p class="lead">A wardrobe archive is not a shopping list. It is a record of useful shapes, materials and combinations that you can return to.</p><a class="btn" href="journal.html">Read the journal</a></div><img src="assets/archive.svg" alt="Wardrobe archive editorial"></div></section>
<section class="section"><div class="wrap"><div class="kicker">07 — Responsible choices</div><h2>Buy with a longer horizon.</h2><p class="lead">Consider repairability, care requirements, versatility and the number of outfits a garment can support. Avoid unsupported sustainability claims; focus on observable product characteristics.</p></div></section>
<section class="section"><div class="wrap"><div class="kicker">08 — The atelier</div><h2>A practical editorial lab for modern wardrobes.</h2><p class="lead">Explore fit studies, material notes, seasonal systems and wardrobe experiments written for real routines.</p><a class="btn" href="about.html">Enter the atelier</a></div></section>
<section class="section"><div class="wrap"><div class="kicker">09 — Start here</div><h2>Find your next useful layer.</h2><p class="lead">Browse the collection by purpose and build from the pieces that solve the most problems.</p><a class="btn" href="collection.html">Open collection</a></div></section>
</main>
<footer><div class="wrap foot"><div><h4>Explore</h4><a href="collection.html">Collection</a><a href="journal.html">Journal</a><a href="about.html">Atelier</a></div><div><h4>Contact</h4><p>3638 Westbourne Grove<br>London, UK, W2 5SH, GB<br>+1 2125559857</p></div><div><h4>Policies</h4><a href="privacy.html">Privacy</a><a href="terms.html">Terms</a><a href="refund.html">Refund</a><a href="shipping.html">Shipping</a></div></div><div class="wrap legal">© 2026 Wardrobe Alpha Edge. Editorial fashion guidance only.</div></footer></body></html>